export const OBJECT_META = {
  Globe: {
    label: "The Globe",
    description: "A world of inspiration. Every great project starts with curiosity about the world around us. Spin it and see where ideas come from.",
    link: "https://sketchfab.com/3d-models/isometric-room-2e832fd256f74427825e42fb2816dc13",
    interaction: "rotate",
    hint: "Hover to spin",
    tags: ["Design", "Inspiration", "Global"],
    funFact: "The globe has 196 countries. I've found inspiration in all of them.",
    outlineColor: "#22d3ee",
  },
  Bottle: {
    label: "The Bottle",
    description: "A satisfying wobble — like the moment just before an idea settles. Sometimes the best things just need a little nudge.",
    link: "https://sketchfab.com",
    interaction: "wobble",
    hint: "Hover or click to wobble",
    tags: ["Physics", "Satisfying", "Fun"],
    funFact: "The wobble frequency matches the resonance of a half-full glass bottle — deeply satisfying to physics nerds.",
    outlineColor: "#a3e635",
  },
  Map: {
    label: "The Map",
    description: "Hover and watch it compress — ideas folded into a plan. Every journey starts somewhere on this map.",
    link: "https://sketchfab.com",
    interaction: "shrink",
    hint: "Hover to compress",
    tags: ["Planning", "Journey", "Navigation"],
    funFact: "The best plans fit on a napkin. Or a very small map.",
    outlineColor: "#fb923c",
  },
  Piano: {
    label: "Piano",
    description: "Every project has rhythm. Click to hear a little melody — music and code share the same obsession with structure, timing, and flow.",
    link: "https://www.cgtrader.com/items/5611471/download-page",
    interaction: "press",
    hint: "Click to play a melody",
    tags: ["Music", "Rhythm", "Craft"],
    funFact: "A standard piano has 88 keys. My keyboard has about the same, and I use them just as passionately.",
    outlineColor: "#e879f9",
  },
  Bird1: {
    label: "Sparrow",
    description: "Free-spirited, always in flight. Traces a wide oval path around the room — never stops, never slows down.",
    link: "https://sketchfab.com",
    interaction: "float",
    hint: "Watch it fly",
    tags: ["Freedom", "Movement", "Life"],
    funFact: "Sparrows can fly at 38 km/h. This one's a bit slower — it's on portfolio time.",
    outlineColor: "#fbbf24",
  },
  Bird2: {
    label: "Swallow",
    description: "Traces a figure-eight through the room. Some paths loop back on themselves — that's how you learn.",
    link: "https://sketchfab.com",
    interaction: "float",
    hint: "Watch it fly",
    tags: ["Pattern", "Learning", "Flight"],
    funFact: "A figure-eight is the symbol for infinity. Fitting for a bird that never lands.",
    outlineColor: "#f472b6",
  },
  Bird3: {
    label: "Dove",
    description: "A lazy, drifting arc through the air. Not every idea needs to rush — some are better slow.",
    link: "https://sketchfab.com",
    interaction: "float",
    hint: "Watch it drift",
    tags: ["Peace", "Flow", "Patience"],
    funFact: "Doves have been symbols of peace for over 3,000 years. This one just vibes.",
    outlineColor: "#c4b5fd",
  },
  Candle: {
    label: "Candle",
    description: "Click to toggle the room's light. Watch the sun set and the candle become the only light source — warm and flickering.",
    link: "https://sketchfab.com",
    interaction: "darkmode",
    hint: "Click for night mode",
    tags: ["Atmosphere", "Light", "Mood"],
    funFact: "The average candle burns for ~9 hours. This one's been running on JavaScript since page load.",
    outlineColor: "#fde68a",
    // Candle flame geometry looks bad with outline — disabled
    noOutline: true,
  },
  Hat: {
    label: "Hat",
    description: "Tips its brim to great ideas — hover to tip, click for a little magic. Wearing many hats is just part of the job.",
    link: "https://sketchfab.com",
    interaction: "tilt",
    hint: "Hover to tip, click for magic",
    tags: ["Identity", "Style", "Roles"],
    funFact: "Tipping a hat was historically a sign of respect. This hat respects every great idea.",
    outlineColor: "#6ee7b7",
  },
  Mirror: {
    label: "Mirror",
    description: "Hover to trigger a light glint — a flash of clarity. Reflection is the beginning of all good design.",
    link: "https://sketchfab.com",
    interaction: "glint",
    hint: "Hover for glint",
    tags: ["Reflection", "Clarity", "Design"],
    funFact: "Light travels at 299,792 km/s. A glint of inspiration can be just as fast.",
    outlineColor: "#e0f2fe",
  },
  Pigeon: {
    label: "Pigeon",
    description: "Watch it peck — a woodpecker-style nod. Completely still until you hover, then springs to life.",
    link: "https://sketchfab.com",
    interaction: "peck",
    hint: "Hover to peck",
    tags: ["Communication", "Delivery", "Charm"],
    funFact: "Pigeons have been used as messengers since 776 BC. Still more reliable than some APIs.",
    outlineColor: "#94a3b8",
  },
}

export const INTERACTIVE_NAMES = Object.keys(OBJECT_META)
